server:
  port: ${PORT:8080}



spring:
  application:
    name: management-backend
  main:
    banner-mode: "off"
    spring:
      h2:
        console.enabled: true
        console.path: /h2-console
        console.settings.trace: false